//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.ConsoleClient.AsmxPlayerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ActualClub {
            get {
                return this.ActualClubField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualClubField, value) != true)) {
                    this.ActualClubField = value;
                    this.RaisePropertyChanged("ActualClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxPlayerServiceReference.PlayerWebServiceSoap")]
    public interface PlayerWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetPlayersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayers", ReplyAction="*")]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse GetPlayers(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse> GetPlayersAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest request);
        
        // CODEGEN: Generating message contract since element name GetPlayerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayer", ReplyAction="*")]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse GetPlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse> GetPlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest request);
        
        // CODEGEN: Generating message contract since element name fname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPlayer", ReplyAction="*")]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse AddPlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse> AddPlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest request);
        
        // CODEGEN: Generating message contract since element name fname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePlayer", ReplyAction="*")]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse UpdatePlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse> UpdatePlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest request);
        
        // CODEGEN: Generating message contract since element name DeletePlayerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePlayer", ReplyAction="*")]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse DeletePlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse> DeletePlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayers", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequestBody Body;
        
        public GetPlayersRequest() {
        }
        
        public GetPlayersRequest(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPlayersRequestBody {
        
        public GetPlayersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponseBody Body;
        
        public GetPlayersResponse() {
        }
        
        public GetPlayersResponse(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] GetPlayersResult;
        
        public GetPlayersResponseBody() {
        }
        
        public GetPlayersResponseBody(WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] GetPlayersResult) {
            this.GetPlayersResult = GetPlayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayer", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequestBody Body;
        
        public GetPlayerRequest() {
        }
        
        public GetPlayerRequest(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetPlayerRequestBody() {
        }
        
        public GetPlayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponseBody Body;
        
        public GetPlayerResponse() {
        }
        
        public GetPlayerResponse(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player GetPlayerResult;
        
        public GetPlayerResponseBody() {
        }
        
        public GetPlayerResponseBody(WebServices.ConsoleClient.AsmxPlayerServiceReference.Player GetPlayerResult) {
            this.GetPlayerResult = GetPlayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayer", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequestBody Body;
        
        public AddPlayerRequest() {
        }
        
        public AddPlayerRequest(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime birth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string origin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string genre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string clubnow;
        
        public AddPlayerRequestBody() {
        }
        
        public AddPlayerRequestBody(string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            this.fname = fname;
            this.lname = lname;
            this.birth = birth;
            this.origin = origin;
            this.genre = genre;
            this.clubnow = clubnow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponseBody Body;
        
        public AddPlayerResponse() {
        }
        
        public AddPlayerResponse(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player AddPlayerResult;
        
        public AddPlayerResponseBody() {
        }
        
        public AddPlayerResponseBody(WebServices.ConsoleClient.AsmxPlayerServiceReference.Player AddPlayerResult) {
            this.AddPlayerResult = AddPlayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePlayer", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequestBody Body;
        
        public UpdatePlayerRequest() {
        }
        
        public UpdatePlayerRequest(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime birth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string origin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string genre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string clubnow;
        
        public UpdatePlayerRequestBody() {
        }
        
        public UpdatePlayerRequestBody(int id, string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            this.id = id;
            this.fname = fname;
            this.lname = lname;
            this.birth = birth;
            this.origin = origin;
            this.genre = genre;
            this.clubnow = clubnow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponseBody Body;
        
        public UpdatePlayerResponse() {
        }
        
        public UpdatePlayerResponse(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player UpdatePlayerResult;
        
        public UpdatePlayerResponseBody() {
        }
        
        public UpdatePlayerResponseBody(WebServices.ConsoleClient.AsmxPlayerServiceReference.Player UpdatePlayerResult) {
            this.UpdatePlayerResult = UpdatePlayerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePlayerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePlayer", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequestBody Body;
        
        public DeletePlayerRequest() {
        }
        
        public DeletePlayerRequest(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePlayerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeletePlayerRequestBody() {
        }
        
        public DeletePlayerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePlayerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponseBody Body;
        
        public DeletePlayerResponse() {
        }
        
        public DeletePlayerResponse(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePlayerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] DeletePlayerResult;
        
        public DeletePlayerResponseBody() {
        }
        
        public DeletePlayerResponseBody(WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] DeletePlayerResult) {
            this.DeletePlayerResult = DeletePlayerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerWebServiceSoapChannel : WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerWebServiceSoapClient : System.ServiceModel.ClientBase<WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap>, WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap {
        
        public PlayerWebServiceSoapClient() {
        }
        
        public PlayerWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.GetPlayers(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest request) {
            return base.Channel.GetPlayers(request);
        }
        
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] GetPlayers() {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequestBody();
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse retVal = ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).GetPlayers(inValue);
            return retVal.Body.GetPlayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse> WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.GetPlayersAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest request) {
            return base.Channel.GetPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersResponse> GetPlayersAsync() {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayersRequestBody();
            return ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).GetPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.GetPlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest request) {
            return base.Channel.GetPlayer(request);
        }
        
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player GetPlayer(int id) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequestBody();
            inValue.Body.id = id;
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse retVal = ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).GetPlayer(inValue);
            return retVal.Body.GetPlayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse> WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.GetPlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest request) {
            return base.Channel.GetPlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerResponse> GetPlayerAsync(int id) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.GetPlayerRequestBody();
            inValue.Body.id = id;
            return ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).GetPlayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.AddPlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest request) {
            return base.Channel.AddPlayer(request);
        }
        
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player AddPlayer(string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.birth = birth;
            inValue.Body.origin = origin;
            inValue.Body.genre = genre;
            inValue.Body.clubnow = clubnow;
            WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse retVal = ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).AddPlayer(inValue);
            return retVal.Body.AddPlayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse> WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.AddPlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest request) {
            return base.Channel.AddPlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerResponse> AddPlayerAsync(string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.AddPlayerRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.birth = birth;
            inValue.Body.origin = origin;
            inValue.Body.genre = genre;
            inValue.Body.clubnow = clubnow;
            return ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).AddPlayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.UpdatePlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest request) {
            return base.Channel.UpdatePlayer(request);
        }
        
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player UpdatePlayer(int id, string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.birth = birth;
            inValue.Body.origin = origin;
            inValue.Body.genre = genre;
            inValue.Body.clubnow = clubnow;
            WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse retVal = ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).UpdatePlayer(inValue);
            return retVal.Body.UpdatePlayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse> WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.UpdatePlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest request) {
            return base.Channel.UpdatePlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerResponse> UpdatePlayerAsync(int id, string fname, string lname, System.DateTime birth, string origin, string genre, string clubnow) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.UpdatePlayerRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.birth = birth;
            inValue.Body.origin = origin;
            inValue.Body.genre = genre;
            inValue.Body.clubnow = clubnow;
            return ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).UpdatePlayerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.DeletePlayer(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest request) {
            return base.Channel.DeletePlayer(request);
        }
        
        public WebServices.ConsoleClient.AsmxPlayerServiceReference.Player[] DeletePlayer(int id) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequestBody();
            inValue.Body.id = id;
            WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse retVal = ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).DeletePlayer(inValue);
            return retVal.Body.DeletePlayerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse> WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap.DeletePlayerAsync(WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest request) {
            return base.Channel.DeletePlayerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerResponse> DeletePlayerAsync(int id) {
            WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest inValue = new WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequest();
            inValue.Body = new WebServices.ConsoleClient.AsmxPlayerServiceReference.DeletePlayerRequestBody();
            inValue.Body.id = id;
            return ((WebServices.ConsoleClient.AsmxPlayerServiceReference.PlayerWebServiceSoap)(this)).DeletePlayerAsync(inValue);
        }
    }
}
